## NumPy Examples 

### Refer to the NumPy documentation at:

1. NumPy User Guide: https://numpy.org/doc/stable/user/index.html
2. NumPy API Guide: https://numpy.org/doc/stable/reference/index.html

In [1]:
import numpy as np

## Vectors, 1 Dimensional Arrays

### Initialization

#### Creating from a list

In [2]:
a = [0.0, 0.1, 0.2]

x = np.array(a)
x

array([0. , 0.1, 0.2])

#### Arrays must be of a uniform type, NumPy will by default use what it can to make this happen

In [3]:
a = [0.0,"0.1", 0.2]

x = np.array(a)
x

array(['0.0', '0.1', '0.2'], dtype='<U32')

#### The dtype flag can be used to force casting

In [4]:
x = np.array(a,dtype=np.float)
x

array([0. , 0.1, 0.2])

#### But will not always work

In [5]:
a = [0.0,"tim",0.2]
x = np.array(a,dtype=np.float)

ValueError: could not convert string to float: 'tim'

#### One can create arrays that are initially filled with zeros or ones

In [7]:
x = np.ones(3)
y = np.zeros(3)

"x",x,"y",y

('x', array([1., 1., 1.]), 'y', array([0., 0., 0.]))

### Array Arithmetic

#### You can do direct math on NumPy Arrays

In [8]:
x = np.array([1.0, 2.0, 3.0])
y = np.array([2.0, 3.0, 4.0])

In [9]:
x + y

array([3., 5., 7.])

In [10]:
x - y

array([-1., -1., -1.])

In [11]:
x * y

array([ 2.,  6., 12.])

#### Arrays have to be the same size

In [12]:
z = np.array([1.0,2.0])

In [13]:
x+z

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

#### Can also do math operations with scalars

In [14]:
x = 3.0 * x
x

array([3., 6., 9.])

### Aggregate Functions

##### There are number of functions that operate on the whole array

In [15]:
a = x.max()
b = x.min()
c = x.sum()
print("Max = {} Min = {} Sum = {}".format(a,b,c))

Max = 9.0 Min = 3.0 Sum = 18.0


### Array Indexing

#### Array indexing in NumPy is similar to that of Python Lists

In [16]:
x = np.array([1.0,2.0,3.0,4.0,5.0,6.0])
a = x[0]
b = x[3]
c = x[0:3]
d = x[2:]

"x",x,"a",a,"b",b,"c",c,"d",d

('x',
 array([1., 2., 3., 4., 5., 6.]),
 'a',
 1.0,
 'b',
 4.0,
 'c',
 array([1., 2., 3.]),
 'd',
 array([3., 4., 5., 6.]))

### Matrices (Multi-Dimensional Arrays)

#### NumPy can also work with matrices, very similar to arrays

In [17]:
x = np.array([[1.0,2.0,3.0],[2.0,3.0,4.0]])
x

array([[1., 2., 3.],
       [2., 3., 4.]])

#### Can also intialize with 1s, zeros, or with a random numbers

In [18]:
x = np.ones((3,2))
y = np.zeros((4,3))
z = np.random.random((3,2))

"x ",x, "y ", y, "z ", z

('x ',
 array([[1., 1.],
        [1., 1.],
        [1., 1.]]),
 'y ',
 array([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]),
 'z ',
 array([[0.36006544, 0.45900849],
        [0.98523917, 0.9375695 ],
        [0.9823637 , 0.17241349]]))

### Matrix Arithemtic

#### Similar to vectors, you can do arithmatic on matrices

In [19]:
x = np.array([[1.0,2.0],[3.0,4.0]])
y = np.ones((2,2))

a = x + y
b = x - y
c = 2.0 * x

"x ", x, "y ", y, "a ", a,"b ", b,"c ", c

('x ',
 array([[1., 2.],
        [3., 4.]]),
 'y ',
 array([[1., 1.],
        [1., 1.]]),
 'a ',
 array([[2., 3.],
        [4., 5.]]),
 'b ',
 array([[0., 1.],
        [2., 3.]]),
 'c ',
 array([[2., 4.],
        [6., 8.]]))

#### Matrices work different, where you may do arithmatic with the arrays not having the same dimensions

In [20]:
x = np.array([[1.0,2.0],[3.0,4.0]])
y = np.array([1.0,2.0])

a = x + y
"x", x, "y", y,"a",a

('x',
 array([[1., 2.],
        [3., 4.]]),
 'y',
 array([1., 2.]),
 'a',
 array([[2., 4.],
        [4., 6.]]))

### Matrix Multiplication

#### NumPy hanlds Matrix / Matrix multiplication through special functions

np.matmul provides a far more powerful set of options that correspond to using BLAS GEMM methods and is equivalent to the result of np.dot in 1-D and 2-D, they differ in higher dimensions

For More on numpy.matmul see: https://numpy.org/doc/stable/reference/generated/numpy.matmul.html

In [21]:
x = np.array([[1.0,2.0],[3.0,4.0]])
y = np.array([[2.0,3.0],[4.0,5.0]])

a = x*y
b = x.dot(y)
c = np.matmul(x,y)

"x",x,"y",y,"a (element wise multiply)",a,"b (dot product)",b,"c (matmul function)",c

('x',
 array([[1., 2.],
        [3., 4.]]),
 'y',
 array([[2., 3.],
        [4., 5.]]),
 'a (element wise multiply)',
 array([[ 2.,  6.],
        [12., 20.]]),
 'b (dot product)',
 array([[10., 13.],
        [22., 29.]]),
 'c (matmul function)',
 array([[10., 13.],
        [22., 29.]]))

### Matrix Aggregations

#### When using aggregation functions, they become a little more powerful and complex

#### One can operate on the whole matrix

In [22]:
x = np.array([[1.0,2.0,3.0],[4.0,5.0,6.0]])

a = x.max()
b = x.min()
c = x.sum()

print("X = \t{}\n\t{}".format(x[0],x[1]))
print("Max = {} Min = {} Sum = {}".format(a,b,c))

X = 	[1. 2. 3.]
	[4. 5. 6.]
Max = 6.0 Min = 1.0 Sum = 21.0


#### Aggregation Functions can also be performed by axis

#### Aggregating along columns add axis=0

In [23]:
x = np.array([[1.0,5.0,3.0],[4.0,2.0,6.0]])

a = x.max(axis=0)
b = x.min(axis=0)
c = x.sum(axis=0)

print("X = \t{}\n\t{}".format(x[0],x[1]))
print("Max = {} Min = {} Sum = {}".format(a,b,c))

X = 	[1. 5. 3.]
	[4. 2. 6.]
Max = [4. 5. 6.] Min = [1. 2. 3.] Sum = [5. 7. 9.]


#### Aggregating along rows add axis=1

In [24]:
x = np.array([[1.0,5.0,3.0],[4.0,2.0,6.0]])

a = x.max(axis=1)
b = x.min(axis=1)
c = x.sum(axis=1)

print("X = \t{}\n\t{}".format(x[0],x[1]))
print("Max = {} Min = {} Sum = {}".format(a,b,c))

X = 	[1. 5. 3.]
	[4. 2. 6.]
Max = [5. 6.] Min = [1. 2.] Sum = [ 9. 12.]


### Matrix Indexing

#### Matrices can be indexed pretty flexibly and straight forwardly

In [25]:
x = np.array([[1.0,5.0,3.0],[4.0,2.0,6.0],[7.0,8.0,9.0]])

a = x[0,1]
b = x[1,2]
c = x[0:2,1]
d = x[1,0:3]
e = x[1:3,0:2]

print("X = \t{}\n\t{}\n\t{}".format(x[0],x[1],x[2]))
print("\nx[0,1] = {}".format(a))
print("\nx[1,2] = {}".format(b))
print("\nx[0:2,1] = {}".format(c))
print("\nx[1,0:3] = {}".format(d))
print("\nx[1:3,0:2] = \t{}\n\t\t{}".format(e[0],e[1]))


X = 	[1. 5. 3.]
	[4. 2. 6.]
	[7. 8. 9.]

x[0,1] = 5.0

x[1,2] = 6.0

x[0:2,1] = [5. 2.]

x[1,0:3] = [4. 2. 6.]

x[1:3,0:2] = 	[4. 2.]
		[7. 8.]


### Transposing and Reshaping

#### Can perform Matrix Transposes by accessing the T member of the array

In [26]:
x = np.array([[1.0,5.0,3.0],[4.0,2.0,6.0]])

a = x.T

print("x = \t{}\n\t{}".format(x[0],x[1]))
print("x_t = \t{}\n\t{}\n\t{}".format(a[0],a[1],a[2]))

x = 	[1. 5. 3.]
	[4. 2. 6.]
x_t = 	[1. 4.]
	[5. 2.]
	[3. 6.]


#### One can reshape any array using the reshape method

In [27]:
x = np.array([[1.0,5.0,3.0, 4.0,2.0,6.0]])

a = x.reshape((2,3))
b = x.reshape((3,2))

print("x = \t{}".format(x[0]))
print("a = \t{}\n\t{}".format(a[0],a[1]))
print("b = \t{}\n\t{}\n\t{}".format(b[0],b[1],b[2]))

x = 	[1. 5. 3. 4. 2. 6.]
a = 	[1. 5. 3.]
	[4. 2. 6.]
b = 	[1. 5.]
	[3. 4.]
	[2. 6.]


### Other Advanced Functions

#### Boolean Masks

Allows one to create a masking array

In [28]:
x = np.random.randint(0,21,15)

mask = (x < 5)

y = x[mask]

print("x = {}".format(x))
print("mask = {}".format(mask))
print("y = {}".format(y))

x = [13 10 14 10  5  8  6  7  7 20 16  7  1  9 10]
mask = [False False False False False False False False False False False False
  True False False]
y = [1]


#### Sorting

In [29]:
a = np.sort(x)
print("sorted = {}".format(a))

sorted = [ 1  5  6  7  7  7  8  9 10 10 10 13 14 16 20]


In [30]:
x = np.array([[1.0,5.0,3.0],[4.0,2.0,6.0]])

a = np.sort(x,axis=1)
b = np.sort(x,axis=0)

print("Sort rows = \t{}\n\t\t{}".format(a[0],a[1]))
print("\nSort cols = \t{}\n\t\t{}".format(b[0],b[1]))

Sort rows = 	[1. 3. 5.]
		[2. 4. 6.]

Sort cols = 	[1. 2. 3.]
		[4. 5. 6.]


#### Casting

Casting allows for you to change the types of elements that an array has

In [31]:
x = np.array([1.0, 2.0, 3.0, 4.5,5.7])

a = x.astype(int)

print("x = {}".format(x))
print("It has type {}".format(x.dtype))
print("a = {}".format(a))
print("The array is now {}".format(a.dtype))

x = [1.  2.  3.  4.5 5.7]
It has type float64
a = [1 2 3 4 5]
The array is now int64


Rounding will not just drop the decimals

In [32]:
b = np.around(x)
c = b.astype("int")

print("b = {}".format(b))
print("b is still type {}".format(b.dtype))
print("c = {}".format(c))
print("c is now type {}".format(c.dtype))

b = [1. 2. 3. 4. 6.]
b is still type float64
c = [1 2 3 4 6]
c is now type int64


#### Vectorizing 

A super efficient way to operate a function over an array

In [33]:
def pow_value(x,k):
    return x**k

x = np.array([1.0,2.0,3.0])

vfunc = np.vectorize(pow_value)

a = vfunc(x,2.0)
b = vfunc(x,10.0)

print("x = {}".format(x))
print("a = {}".format(a))
print("b = {}".format(b))

x = [1. 2. 3.]
a = [1. 4. 9.]
b = [1.0000e+00 1.0240e+03 5.9049e+04]


Top operate over a 1-D slice using apply_along_axis

In [45]:
x = np.arange(9).astype(np.double).reshape(3,3)

a = np.apply_along_axis(np.sum,0,x)
b = np.apply_along_axis(np.sum,1,x)

#### with another argument
c = np.apply_along_axis(pow_value,0,x,2.0)

print("x = \t{}\n\t{}\n\t{}".format(x[0],x[1],x[2]))
print("\na = \t{}".format(a))
print("\nb = \t{}\n\t{}\n\t{}".format(b[0],b[1],b[2]))
print("\nc = \t{}\n\t{}\n\t{}".format(c[0],c[1],c[2]))

x = 	[0. 1. 2.]
	[3. 4. 5.]
	[6. 7. 8.]

a = 	[ 9. 12. 15.]

b = 	3.0
	12.0
	21.0

c = 	[0. 1. 4.]
	[ 9. 16. 25.]
	[36. 49. 64.]


Operating over multiple axis can also be done with apply_over_axis

In [43]:
x = np.arange(9).astype(np.double).reshape(3,3)

a = np.apply_over_axes(np.sum, x,[0])
b = np.apply_over_axes(np.sum, x, [1])
c = np.apply_over_axes(np.sum, x, [0,1])

print("x = \t{}\n\t{}\n\t{}".format(x[0],x[1],x[2]))
print("\na = \t{}".format(a))
print("\nb = \t{}\n\t{}\n\t{}".format(b[0],b[1],b[2]))
print("\nc = \t{}".format(c))

x = 	[0. 1. 2.]
	[3. 4. 5.]
	[6. 7. 8.]

a = 	[[ 9. 12. 15.]]

b = 	[3.]
	[12.]
	[21.]

c = 	[[36.]]
